name: Repository Setup and Welcome

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  setup-repository:
    name: Step 0 - Welcome and Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Initialize Step Counter
        id: setup-step
        run: |
          mkdir -p .github/steps
          if [ ! -f .github/steps/-step.txt ]; then
            echo "0" > .github/steps/-step.txt
          fi
          echo "Current step: $(cat .github/steps/-step.txt)"

      - name: Validate Step Counter
        run: |
          STEP=$(cat .github/steps/-step.txt)
          if ! [[ "$STEP" =~ ^[0-9]+$ ]]; then
            echo "Error: Step counter is invalid."
            exit 1
          fi

  welcome-message:
    name: Post Welcome Message
    needs: setup-repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Post Welcome Comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number || 1,  // Default to issue/PR #1 if none provided
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Welcome to the repository!'
             });

      - name: Greet Repository Visitor
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Repository Visitor'
