name: "Step 2 - Add a Job"

on:
  workflow_dispatch:
  push:
    branches:
      - welcome-workflow

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check Current Step
    runs-on: ubuntu-latest
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
      is_valid: ${{ steps.validate_step.outputs.is_valid }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get Current Step
        id: get_step
        run: |
          if [ -f ./.github/steps/-step.txt ]; then
            echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
          else
            echo "Error: Step file not found"
            exit 1
          fi

      - name: Validate Step
        id: validate_step
        run: |
          STEP=$(cat ./.github/steps/-step.txt)
          if [[ "$STEP" == "2" ]]; then
            echo "is_valid=true" >> $GITHUB_OUTPUT
          else
            echo "is_valid=false" >> $GITHUB_OUTPUT
          fi

  validate_jobs:
    name: Validate Welcome Workflow Jobs
    needs: get_current_step
    if: >-
      ${{ !github.event.repository.is_template &&
          needs.get_current_step.outputs.current_step == 2 &&
          needs.get_current_step.outputs.is_valid == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Workflow File
        id: check_file
        run: |
          if [ ! -f ".github/workflows/welcome.yml" ]; then
            echo "Error: welcome.yml workflow file not found"
            exit 1
          fi

      - name: Validate Basic Structure
        uses: skills/action-check-file@v1
        with:
          file: ".github/workflows/welcome.yml"
          search: "jobs:"

      - name: Detailed Job Validation
        run: |
          WORKFLOW_FILE=".github/workflows/welcome.yml"
          
          # Check for required job elements
          if ! grep -q "jobs:" "$WORKFLOW_FILE"; then
            echo "Error: Missing jobs section"
            exit 1
          fi
          
          # Check for at least one job definition
          if ! grep -q "  [a-zA-Z0-9_-]*:" "$WORKFLOW_FILE" || \
             ! grep -q "    runs-on:" "$WORKFLOW_FILE"; then
            echo "Error: No properly defined jobs found"
            exit 1
          fi
          
          # Verify job has required elements
          if ! grep -q "    steps:" "$WORKFLOW_FILE"; then
            echo "Error: Job missing steps section"
            exit 1
          fi

      - name: Update Progress
        if: success()
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: 3
          branch_name: welcome-workflow

  provide_feedback:
    name: Provide Feedback
    needs: [get_current_step, validate_jobs]
    if: always()
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Results
        run: |
          if [ "${{ needs.validate_jobs.result }}" == "success" ]; then
            echo "✅ Job validation successful! Moving to step 3."
            echo "Your workflow now has properly configured jobs."
          else
            echo "❌ Some issues were found. Please check:"
            echo "  - Ensure your workflow file exists at .github/workflows/welcome.yml"
            echo "  - Verify you have added a 'jobs:' section"
            echo "  - Make sure each job has:"
            echo "    * A unique name"
            echo "    * A 'runs-on:' parameter"
            echo "    * A 'steps:' section"
            echo ""
            echo "Example of a valid job:"
            echo "jobs:"
            echo "  welcome-job:"
            echo "    runs-on: ubuntu-latest"
            echo "    steps:"
            echo "      - name: Welcome Message"
            echo "        run: echo 'Hello!'"
          fi

  cleanup:
    name: Cleanup Check
    needs: [validate_jobs]
    if: always()
    runs-on: ubuntu-latest
    
    steps:
      - name: Verify Job Status
        if: needs.validate_jobs.result != 'success'
        run: |
          echo "Job validation did not succeed. Please fix the issues and try again."
          exit 1
