name: "Step 3 - Add Actions"

on:
  workflow_dispatch:
  push:
    branches:
      - welcome-workflow

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check Current Step
    runs-on: ubuntu-latest
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
      is_valid: ${{ steps.validate_step.outputs.is_valid }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get Current Step
        id: get_step
        run: |
          STEP_FILE=".github/steps/-step.txt"
          if [ -f "$STEP_FILE" ]; then
            CURRENT_STEP=$(cat "$STEP_FILE")
            echo "current_step=$CURRENT_STEP" >> $GITHUB_OUTPUT
          else
            echo "Error: Step file not found"
            exit 1
          fi

      - name: Validate Step
        id: validate_step
        run: |
          STEP=$(cat ./.github/steps/-step.txt)
          if [[ "$STEP" == "3" ]]; then
            echo "is_valid=true" >> $GITHUB_OUTPUT
          else
            echo "is_valid=false" >> $GITHUB_OUTPUT

  validate_actions:
    name: Validate Workflow Actions
    needs: get_current_step
    if: >-
      ${{ !github.event.repository.is_template &&
          needs.get_current_step.outputs.current_step == '3' &&
          needs.get_current_step.outputs.is_valid == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Validate Steps and Actions
        run: |
          WORKFLOW_FILE=".github/workflows/welcome.yml"

          # Ensure workflow file exists
          if [ ! -f "$WORKFLOW_FILE" ]; then
            echo "Error: Workflow file '$WORKFLOW_FILE' not found."
            exit 1
          fi

          # Validate steps section
          if ! grep -q "    steps:" "$WORKFLOW_FILE"; then
            echo "Error: Missing 'steps:' section in the workflow."
            exit 1
          fi

          # Validate action usage
          if ! grep -q "      uses:" "$WORKFLOW_FILE"; then
            echo "Error: No GitHub Actions are used in the workflow."
            exit 1
          fi

          # Check for required action components
          if ! grep -q "actions/checkout@" "$WORKFLOW_FILE"; then
            echo "Warning: 'actions/checkout@' is missing. It's recommended for accessing repository files."
          fi

          # Ensure each step has a name
          if ! grep -q "      - name:" "$WORKFLOW_FILE"; then
            echo "Error: Each step must have a descriptive 'name'."
            exit 1
          fi

      - name: List Actions Used
        run: |
          echo "Actions used in the workflow:"
          grep "uses:" .github/workflows/welcome.yml || echo "No actions found."

      - name: Update Progress
        if: success()
        run: |
          STEP_FILE=".github/steps/-step.txt"
          echo "4" > "$STEP_FILE"
          echo "Step updated to 4."

  provide_feedback:
    name: Provide Feedback
    needs: [validate_actions]
    if: always()
    runs-on: ubuntu-latest
    
    steps:
      - name: Action Validation Results
        run: |
          if [ "${{ needs.validate_actions.result }}" == "success" ]; then
            echo "✅ Actions validation successful! You are now on step 4."
            echo "Your workflow includes properly configured actions."
          else
            echo "❌ Some issues were found. Please address the following:"
            echo "  - Ensure the 'steps:' section is included in your jobs."
            echo "  - Add at least one GitHub Action using 'uses:'."
            echo "  - Every step should have a descriptive 'name'."
            echo ""
            echo "Example of valid step with actions:"
            echo "jobs:"
            echo "  example-job:"
            echo "    runs-on: ubuntu-latest"
            echo "    steps:"
            echo "      - name: Checkout Code"
            echo "        uses: actions/checkout@v4"
            echo "      - name: Greet User"
            echo "        uses: actions/hello-world-javascript-action@v1"
            echo "        with:"
            echo "          who-to-greet: 'GitHub User'"

  cleanup:
    name: Cleanup Check
    needs: [validate_actions]
    if: always()
    runs-on: ubuntu-latest
    
    steps:
      - name: Verify Action Status
        if: needs.validate_actions.result != 'success'
        run: |
          echo "❌ Action validation did not succeed. Please fix the identified issues and try again."
          exit 1
