name: "Step 5 - Trigger Workflow"

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Post welcome comment
    types:
      - completed

permissions:
  contents: write
  actions: read

jobs:
  get_current_step:
    name: Check Current Step
    runs-on: ubuntu-latest
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
      is_valid: ${{ steps.validate_step.outputs.is_valid }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get Current Step
        id: get_step
        run: |
          if [ -f ./.github/steps/-step.txt ]; then
            echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
          else
            echo "Error: Step file not found"
            exit 1
          fi

      - name: Validate Step
        id: validate_step
        run: |
          STEP=$(cat ./.github/steps/-step.txt)
          if [[ "$STEP" == "5" ]]; then
            echo "is_valid=true" >> $GITHUB_OUTPUT
          else
            echo "is_valid=false" >> $GITHUB_OUTPUT
          fi

  verify_workflow_trigger:
    name: Verify Workflow Trigger
    needs: get_current_step
    if: >-
      ${{ !github.event.repository.is_template &&
          needs.get_current_step.outputs.current_step == 5 &&
          needs.get_current_step.outputs.is_valid == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Welcome Workflow
        id: check_workflow
        run: |
          if [ ! -f ".github/workflows/welcome.yml" ]; then
            echo "Error: welcome.yml workflow not found"
            exit 1
          fi

      - name: Verify Workflow Run
        id: verify_run
        run: |
          # Check if the workflow has been triggered
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            echo "workflow_triggered=true" >> $GITHUB_OUTPUT
            echo "Workflow was successfully triggered and completed"
          else
            echo "workflow_triggered=false" >> $GITHUB_OUTPUT
            echo "Workflow hasn't been triggered or completed yet"
          fi

      - name: Update Progress
        if: steps.verify_run.outputs.workflow_triggered == 'true'
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 5
          to_step: X
          branch_name: test-workflow

  provide_feedback:
    name: Provide Feedback
    needs: [get_current_step, verify_workflow_trigger]
    if: always()
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Results
        run: |
          if [ "${{ needs.verify_workflow_trigger.result }}" == "success" ]; then
            echo "✅ Workflow trigger verification successful!"
            echo "Congratulations! You've completed all steps!"
          else
            echo "❌ Some items need attention:"
            echo "  - Check if welcome.yml exists in .github/workflows/"
            echo "  - Verify the workflow has been triggered"
            echo "  - Ensure the welcome comment workflow completed successfully"
            echo ""
            echo "To trigger the workflow:"
            echo "1. Make a change to trigger the workflow"
            echo "2. Push the change to your repository"
            echo "3. Go to the Actions tab to monitor the workflow"
          fi

  completion_check:
    name: Final Completion Check
    needs: [verify_workflow_trigger]
    if: always()
    runs-on: ubuntu-latest
    
    steps:
      - name: Final Status
        run: |
          if [ "${{ needs.verify_workflow_trigger.result }}" == "success" ]; then
            echo "🎉 Congratulations! You've completed the GitHub Actions course!"
            echo "Here's what you've learned:"
            echo "  ✓ Creating workflows"
            echo "  ✓ Adding jobs and steps"
            echo "  ✓ Using actions"
            echo "  ✓ Triggering workflows"
            echo "  ✓ Managing workflow runs"
          else
            echo "Keep going! You're almost there!"
            echo "Need help? Check the workflow run logs for detailed feedback."
          fi
