name: "Step 5 - Trigger Workflow"

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Post welcome comment # Replace with the exact name of the triggering workflow
    types:
      - completed

permissions:
  contents: write
  actions: read

jobs:
  get_current_step:
    name: Check Current Step
    runs-on: ubuntu-latest
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
      is_valid: ${{ steps.validate_step.outputs.is_valid }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get Current Step
        id: get_step
        run: |
          if [ -f ./.github/steps/-step.txt ]; then
            echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
          else
            echo "Error: Step file not found"
            exit 1
          fi

      - name: Validate Step
        id: validate_step
        run: |
          STEP=$(cat ./.github/steps/-step.txt)
          if [[ "$STEP" == "5" ]]; then
            echo "is_valid=true" >> $GITHUB_OUTPUT
          else
            echo "is_valid=false" >> $GITHUB_OUTPUT
          fi

  verify_workflow_trigger:
    name: Verify Workflow Trigger
    needs: get_current_step
    if: >-
      ${{ needs.get_current_step.outputs.current_step == 5 &&
          needs.get_current_step.outputs.is_valid == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Workflow File
        id: check_workflow
        run: |
          if [ ! -f ".github/workflows/welcome.yml" ]; then
            echo "Error: welcome.yml workflow not found"
            exit 1
          fi

      - name: Verify Triggering Workflow Run
        id: verify_run
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            echo "workflow_triggered=true" >> $GITHUB_OUTPUT
          else
            echo "workflow_triggered=false" >> $GITHUB_OUTPUT
            echo "Triggering workflow has not completed successfully"
          fi

      - name: Update Progress
        if: steps.verify_run.outputs.workflow_triggered == 'true'
        run: |
          STEP_FILE=".github/steps/-step.txt"
          echo "6" > "$STEP_FILE"
          echo "Step progress updated to 6."

  provide_feedback:
    name: Provide Feedback
    needs: [get_current_step, verify_workflow_trigger]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Actionable Feedback
        run: |
          if [ "${{ needs.verify_workflow_trigger.result }}" == "success" ]; then
            echo "✅ Workflow triggered and completed successfully!"
            echo "Congratulations! You've completed Step 5."
          else
            echo "❌ Workflow trigger validation failed. Please check:"
            echo "  - Ensure the 'Post welcome comment' workflow exists and is configured correctly."
            echo "  - Verify the workflow completes successfully."
            echo ""
            echo "Manual Trigger Steps:"
            echo "1. Make a change to your repository to trigger the workflow."
            echo "2. Push the change."
            echo "3. Monitor the workflow under the Actions tab."
          fi

  completion_check:
    name: Final Completion Check
    needs: verify_workflow_trigger
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Final Summary
        run: |
          if [ "${{ needs.verify_workflow_trigger.result }}" == "success" ]; then
            echo "🎉 Congratulations! You've successfully completed the GitHub Actions course!"
            echo "Here's a summary of your achievements:"
            echo "  ✓ Created workflows"
            echo "  ✓ Added jobs and steps"
            echo "  ✓ Utilized GitHub Actions"
            echo "  ✓ Triggered and validated workflows"
            echo "  ✓ Managed workflow runs"
          else
            echo "Keep going! You're so close to finishing."
            echo "Refer to the provided feedback to fix any issues."
