strategy:
  matrix:
    language: ['python', 'javascript', 'java', 'go', 'cpp']

on:
  schedule:
    - cron: '0 3 * * 0' # Every Sunday at 3 AM

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ['python', 'javascript', 'java', 'go', 'cpp']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          config-file: ./.github/codeql/config.yml

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Upload Analysis Reports
        uses: actions/upload-artifact@v3
        with:
          name: codeql-reports-${{ matrix.language }}
          path: ./.github/codeql-reports/

  license-check:
    name: Dependency License Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: License Scanner
        uses: actions/dependency-review-action@v3
